name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.2.0-beta.6
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues

dependencies:
  meta: 1.9.1
  path: ^1.8.3
  gql: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0+1
  gql_http_link: ^1.0.1+1
  gql_transform_link: ^1.0.0
  gql_error_link: ^1.0.0+1
  gql_dedupe_link: ^2.0.3+1
  hive: ^2.2.3
  normalize: ^0.9.0
  http: ^1.1.0
  collection: 1.17.2
  web_socket_channel: ^2.4.0
  stream_channel: 2.1.1
  rxdart: ^0.27.7
  uuid: ^4.2.1

dev_dependencies:
  async: ^2.5.0
  mockito: ^5.0.0
  test: ^1.16.0
  coverage: ^1.0.3
  http_parser: ^4.0.0
  lints: ^1.0.1

environment:
  sdk: '>=2.15.0 <4.0.0'
